// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: grpc/proto/audio_processing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioProcessor_ProcessAudio_FullMethodName       = "/audio.AudioProcessor/ProcessAudio"
	AudioProcessor_ProcessAudioStream_FullMethodName = "/audio.AudioProcessor/ProcessAudioStream"
)

// AudioProcessorClient is the client API for AudioProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioProcessorClient interface {
	ProcessAudio(ctx context.Context, in *AudioChunk, opts ...grpc.CallOption) (*AudioChunk, error)
	ProcessAudioStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AudioChunk], error)
}

type audioProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioProcessorClient(cc grpc.ClientConnInterface) AudioProcessorClient {
	return &audioProcessorClient{cc}
}

func (c *audioProcessorClient) ProcessAudio(ctx context.Context, in *AudioChunk, opts ...grpc.CallOption) (*AudioChunk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioChunk)
	err := c.cc.Invoke(ctx, AudioProcessor_ProcessAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioProcessorClient) ProcessAudioStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioProcessor_ServiceDesc.Streams[0], AudioProcessor_ProcessAudioStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, AudioChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioProcessor_ProcessAudioStreamClient = grpc.BidiStreamingClient[AudioChunk, AudioChunk]

// AudioProcessorServer is the server API for AudioProcessor service.
// All implementations must embed UnimplementedAudioProcessorServer
// for forward compatibility.
type AudioProcessorServer interface {
	ProcessAudio(context.Context, *AudioChunk) (*AudioChunk, error)
	ProcessAudioStream(grpc.BidiStreamingServer[AudioChunk, AudioChunk]) error
	mustEmbedUnimplementedAudioProcessorServer()
}

// UnimplementedAudioProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioProcessorServer struct{}

func (UnimplementedAudioProcessorServer) ProcessAudio(context.Context, *AudioChunk) (*AudioChunk, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessAudio not implemented")
}
func (UnimplementedAudioProcessorServer) ProcessAudioStream(grpc.BidiStreamingServer[AudioChunk, AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method ProcessAudioStream not implemented")
}
func (UnimplementedAudioProcessorServer) mustEmbedUnimplementedAudioProcessorServer() {}
func (UnimplementedAudioProcessorServer) testEmbeddedByValue()                        {}

// UnsafeAudioProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioProcessorServer will
// result in compilation errors.
type UnsafeAudioProcessorServer interface {
	mustEmbedUnimplementedAudioProcessorServer()
}

func RegisterAudioProcessorServer(s grpc.ServiceRegistrar, srv AudioProcessorServer) {
	// If the following call panics, it indicates UnimplementedAudioProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioProcessor_ServiceDesc, srv)
}

func _AudioProcessor_ProcessAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioProcessorServer).ProcessAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioProcessor_ProcessAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioProcessorServer).ProcessAudio(ctx, req.(*AudioChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioProcessor_ProcessAudioStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioProcessorServer).ProcessAudioStream(&grpc.GenericServerStream[AudioChunk, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioProcessor_ProcessAudioStreamServer = grpc.BidiStreamingServer[AudioChunk, AudioChunk]

// AudioProcessor_ServiceDesc is the grpc.ServiceDesc for AudioProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioProcessor",
	HandlerType: (*AudioProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAudio",
			Handler:    _AudioProcessor_ProcessAudio_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessAudioStream",
			Handler:       _AudioProcessor_ProcessAudioStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/proto/audio_processing.proto",
}
