// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grpc/proto/audio_processing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	Format        int32                  `protobuf:"varint,4,opt,name=format,proto3" json:"format,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_grpc_proto_audio_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_audio_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_grpc_proto_audio_processing_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioChunk) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *AudioChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_grpc_proto_audio_processing_proto protoreflect.FileDescriptor

const file_grpc_proto_audio_processing_proto_rawDesc = "" +
	"\n" +
	"!grpc/proto/audio_processing.proto\x12\x05audio\"\x9e\x01\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x12\x16\n" +
	"\x06format\x18\x04 \x01(\x05R\x06format\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\x86\x01\n" +
	"\x0eAudioProcessor\x124\n" +
	"\fProcessAudio\x12\x11.audio.AudioChunk\x1a\x11.audio.AudioChunk\x12>\n" +
	"\x12ProcessAudioStream\x12\x11.audio.AudioChunk\x1a\x11.audio.AudioChunk(\x010\x01B\x12Z\x10audio/grpc/protob\x06proto3"

var (
	file_grpc_proto_audio_processing_proto_rawDescOnce sync.Once
	file_grpc_proto_audio_processing_proto_rawDescData []byte
)

func file_grpc_proto_audio_processing_proto_rawDescGZIP() []byte {
	file_grpc_proto_audio_processing_proto_rawDescOnce.Do(func() {
		file_grpc_proto_audio_processing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_audio_processing_proto_rawDesc), len(file_grpc_proto_audio_processing_proto_rawDesc)))
	})
	return file_grpc_proto_audio_processing_proto_rawDescData
}

var file_grpc_proto_audio_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_proto_audio_processing_proto_goTypes = []any{
	(*AudioChunk)(nil), // 0: audio.AudioChunk
}
var file_grpc_proto_audio_processing_proto_depIdxs = []int32{
	0, // 0: audio.AudioProcessor.ProcessAudio:input_type -> audio.AudioChunk
	0, // 1: audio.AudioProcessor.ProcessAudioStream:input_type -> audio.AudioChunk
	0, // 2: audio.AudioProcessor.ProcessAudio:output_type -> audio.AudioChunk
	0, // 3: audio.AudioProcessor.ProcessAudioStream:output_type -> audio.AudioChunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_audio_processing_proto_init() }
func file_grpc_proto_audio_processing_proto_init() {
	if File_grpc_proto_audio_processing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_audio_processing_proto_rawDesc), len(file_grpc_proto_audio_processing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_audio_processing_proto_goTypes,
		DependencyIndexes: file_grpc_proto_audio_processing_proto_depIdxs,
		MessageInfos:      file_grpc_proto_audio_processing_proto_msgTypes,
	}.Build()
	File_grpc_proto_audio_processing_proto = out.File
	file_grpc_proto_audio_processing_proto_goTypes = nil
	file_grpc_proto_audio_processing_proto_depIdxs = nil
}
